import { Product, Category } from '../types';

export const categories: Category[] = [
  { id: '1', name: 'Мебель', icon: '🪑', productCount: 45 },
  { id: '2', name: 'Текстиль', icon: '🛏️', productCount: 32 },
  { id: '3', name: 'Освещение', icon: '💡', productCount: 28 },
  { id: '4', name: 'Декор', icon: '🖼️', productCount: 67 },
  { id: '5', name: 'Кухня', icon: '🍽️', productCount: 54 },
  { id: '6', name: 'Ванная', icon: '🚿', productCount: 23 },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Диван "Комфорт"',
    price: 45000,
    description: 'Удобный диван для гостиной с мягкими подушками',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400',
    category: '1',
    inStock: true,
    rating: 4.5,
    reviews: 23,
  },
  {
    id: '2',
    name: 'Кресло "Релакс"',
    price: 18000,
    description: 'Эргономичное кресло для отдыха',
    image: 'https://images.unsplash.com/photo-1592078615290-033ee584e267?w=400',
    category: '1',
    inStock: true,
    rating: 4.8,
    reviews: 15,
  },
  {
    id: '3',
    name: 'Постельное белье "Люкс"',
    price: 5500,
    description: 'Комплект постельного белья из египетского хлопка',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400',
    category: '2',
    inStock: true,
    rating: 5.0,
    reviews: 42,
  },
  {
    id: '4',
    name: 'Люстра "Кристалл"',
    price: 25000,
    description: 'Хрустальная люстра для гостиной',
    image: 'https://images.unsplash.com/photo-1565636192180-1fcd0e3c9d5a?w=400',
    category: '3',
    inStock: true,
    rating: 4.7,
    reviews: 8,
  },
  {
    id: '5',
    name: 'Картина "Абстракция"',
    price: 8000,
    description: 'Современная картина для интерьера',
    image: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=400',
    category: '4',
    inStock: true,
    rating: 4.3,
    reviews: 12,
  },
  {
    id: '6',
    name: 'Набор посуды',
    price: 12000,
    description: 'Керамический набор посуды на 6 персон',
    image: 'https://images.unsplash.com/photo-1525974154734-0b0374f54f4f?w=400',
    category: '5',
    inStock: true,
    rating: 4.6,
    reviews: 31,
  },
];